### ISSUE TITLE
attrib or pemission on assets an runtime

### ISSUE THREAD

**Issue by aguchoca** [masteringyii/chapter2#1]
The chmodr or attirb or anythinng that I do for  changing the read-only property never works.

**Comment by charlesportwoodii** [comment]
The source code listed here is for an unreleased book "Mastering Yii", which will be published by Packt Publishing later this year. The source code identified here may or may not be finalized, and is subject to change until the book is published. Furthermore, the instructions outlined here are designed to work in conjunction with the instructions listed in the book, which specifically outline the use of a Linux virtual machine (a Vagrant box running Ubuntu to be specific) for use of the source code listed here. Other configurations will not be supported.

On Linux, the commands you need to run are:

```
chmod -R 775 /path/to/runtime
chmod -R 775 /path/to/assets
```

That being said, the source code listed here is provided AS-IS, is a WORK IN PROGRESS, and customer support will not be provided until the book is published.
